/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "GPIO.h"
#include "BasicTIM.h"
#include "Utilities.h"
#include "Hal.h"
#include "SysTick_red.h"
#include "usb_device.h"
#include "adasMngr.h"
#include "DMA.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    halInit();

    uint8 msg[] = "szia\n";
    uint8 Rx[8];
    uint16 RxLen = 0;
    uint32 Time = SysTick_GetTicks();

    uint32 a[5] = {0x01234567,0x89abcdef,0x01234567,0x89abcdef,0x01234567};
    uint32 b[5] = {0,0,0,0,0};
    uint8 adas = 0;

    dtDMA_S0CR DmaConfig = {.Word = 0};
    DmaConfig.Field.CHSEL = DMA_CS3;
    DmaConfig.Field.MSIZE = DMA_MEM_32;
    DmaConfig.Field.PSIZE = DMA_PER_8;
    DmaConfig.Field.MINC = 1;
    DmaConfig.Field.DIR = DMA_PER2MEM;
    DmaConfig.Field.PBURST = 0;

    /* Loop forever */
	for(;;)
	{
	    adasMngr_Loop();
	    if(IsPassed(Time, 1000))
	    {
	        Time = SysTick_GetTicks();

	        USB_Transmit(msg, 5);
	    }
	    if(RxLen == 0) RxLen = USB_Receive(Rx, 8);
        if(RxLen != 0)
        {
            if(USB_Transmit(Rx, RxLen) == 0)
            {
                RxLen = 0;
            }
        }
        if(adas == 0)
        {
            if(adasMngr_SetState(AdasMngrState_Testing) == TransitionDone) adas = 1;
        }
        else if(adas == 2)
        {
            if(adasMngr_SetState(AdasMngrState_Stopped) == TransitionDone) adas = 3;
        }
	}
}


