/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "GPIO.h"
#include "BasicTIM.h"
#include "Utilities.h"
#include "Hal.h"
#include "SysTick_red.h"
#include "usb_device.h"
#include "adasMngr.h"
#include "DMA.h"
#include "SPI.h"
#include "Filters/Filters_Task.h"
#include "Filters/Filters_Proc.h"
#include "Prj_Types.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    halInit();
    uint8 adas = 0;
    uint32 data[16];
    uint8 dataSize = 0;
    dtEcgData t;
    uint8 cntr = 0;

    uint32 outBuffer[16];
    uint8 outSize = 0;

    /* Loop forever */
	for(;;)
	{
	    adasMngr_Loop();
	    Filters_Runnable();
	    DataHandler_Runnable();
	    Com_Runnable();

        if(adas == 0)
        {
            if(adasMngr_SetState(AdasMngrState_Testing) == TransitionDone) adas = 1;
        }
	}
}
